on:
  workflow_dispatch:
    inputs:
      previousVersion:
        description: 'Previous Version (Do not include v prefix, must be same as the last version tag! Example: 1.4.1)'
        required: true
      version:
        description: 'Version (Do not include v prefix! Example: 1.4.2)'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Fetch tags
        run: git fetch --tags
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Upload to websites
        run: ./gradlew publishThirdParty --stacktrace -PlastTag="v${{ github.event.inputs.previousVersion }}" -PcurrentTag="v${{ github.event.inputs.version }}"
        if: |
          !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.pull_request.title, '[ci skip]')
        env:
          modrinth_token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge_token: ${{ secrets.CURSEFORGE_TOKEN }}
          github_token: ${{ secrets.GH_API_KEY }}
          discord_release_webhook: ${{ secrets.DISCORD_ANNOUNCEMENT_WEBHOOK }}
      - name: Capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/